language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"

sudo: required

cache: pip

before_install:
  - python -m pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install git+https://github.com/KrishnaswamyLab/graphtools@dev

install:
  - cd Python; pip install -U .
  - cd ..

script:
  - python -c "import phate"
  - cd Python; pip install -U .[test]
  - python setup.py test
  - pip install -U .[doc]
  - python setup.py build_sphinx

deploy:
  provider: pypi
  user: scottgigante
  password: ${PYPI_PASSWORD}
  distributions: sdist bdist_wheel
  skip_existing: true
  skip_cleanup: true
  on:
    tags: true
    branch: master
