  language: python
  python:
    - "2.7"
    - "3.5"
    - "3.6"

  sudo: required

  before_install:
    - pip install nose2

  install:
    - cd Python
    - python setup.py install
    - cd ..

  script:
    - cd Python
    - python setup.py test
